+incdir+$RIDECODE_PATH/src/fpga/
$RIDECODE_PATH/src/fpga/alloc_issue_ino.v
$RIDECODE_PATH/src/fpga/alu.v
$RIDECODE_PATH/src/fpga/arf.v
$RIDECODE_PATH/src/fpga/brimm_gen.v
$RIDECODE_PATH/src/fpga/btb.v
$RIDECODE_PATH/src/fpga/decoder.v
$RIDECODE_PATH/src/fpga/define.v
$RIDECODE_PATH/src/fpga/dmem.v
$RIDECODE_PATH/src/fpga/dualport_ram.v
$RIDECODE_PATH/src/fpga/exunit_alu.v
$RIDECODE_PATH/src/fpga/exunit_branch.v
$RIDECODE_PATH/src/fpga/exunit_ldst.v
$RIDECODE_PATH/src/fpga/exunit_mul.v
$RIDECODE_PATH/src/fpga/gshare.v
$RIDECODE_PATH/src/fpga/imem.v
$RIDECODE_PATH/src/fpga/imem_outa.v
$RIDECODE_PATH/src/fpga/imm_gen.v
$RIDECODE_PATH/src/fpga/mpft.v
$RIDECODE_PATH/src/fpga/multiplier.v
$RIDECODE_PATH/src/fpga/pipeline_if.v
$RIDECODE_PATH/src/fpga/pipeline.v
$RIDECODE_PATH/src/fpga/prioenc.v
$RIDECODE_PATH/src/fpga/ram_sync_nolatch.v
$RIDECODE_PATH/src/fpga/ram_sync.v
$RIDECODE_PATH/src/fpga/reorderbuf.v
$RIDECODE_PATH/src/fpga/rrf_freelistmanager.v
$RIDECODE_PATH/src/fpga/rrf.v
$RIDECODE_PATH/src/fpga/rs_alu.v
$RIDECODE_PATH/src/fpga/rs_branch.v
$RIDECODE_PATH/src/fpga/rs_ldst.v
$RIDECODE_PATH/src/fpga/rs_mul.v
$RIDECODE_PATH/src/fpga/rs_reqgen.v
$RIDECODE_PATH/src/fpga/src_manager.v
$RIDECODE_PATH/src/fpga/srcopr_manager.v
$RIDECODE_PATH/src/fpga/srcsel.v
$RIDECODE_PATH/src/fpga/storebuf.v
//$RIDECODE_PATH/src/fpga/system.v
$RIDECODE_PATH/src/fpga/tag_generator.v
$RIDECODE_PATH/src/fpga/oldest_finder.v
$RIDECODE_PATH/src/fpga/storebuf.v
$RIDECODE_PATH/src/fpga/search_be.v
$RIDECODE_PATH/src/fpga/topsim.v
